### ISSUE TITLE
Add vet concerns to notes

### ISSUE THREAD

**Issue by skyheat** [codersforcauses/poops#180]
**Is your feature request related to a problem? Please describe.**
Vet concerns are currently not added to the notes of the specific visit.

**Describe the solution you'd like**
Vet concerns should be added to the notes of the specific visit.
And also add the vet concerns to a collection called `vet_concerns`.
The schema for the document should be:
```yaml
/vet_concerns
  /{vet_concern}
    - user_uid: string
    - user_name: string
    - user_email: string
    - user_phone?: integer
    - client_name: string
    - pet_name: string
    - visit_time: timestamp
    - visit_id: string
    - detail: string
    - created_at: timestamp
```
**Describe alternatives you've considered**

**Additional context**
