### ISSUE TITLE
Create `Incident` page for admins

### ISSUE THREAD

**Issue by NicholasChoong** [codersforcauses/poops#181]
- List the `incidents` down (use mock data for now)
- You can use the components in the `Visit` page
- The `incident` doc schema:
```yaml
/incidents
  /{incident}
    - user_uid: string
    - user_name: string
    - user_email: string
    - user_phone?: integer
    - client_name: string
    - pet_name: string
    - visit_time: timestamp
    - visit_id: string
    - detail: string
    - created_at: timestamp
```
