### ISSUE TITLE
Create `Roles` page for admins

### ISSUE THREAD

**Issue by NicholasChoong** [codersforcauses/poops#183]
- List the `roles` documents down (use mock data for now)
- An `email` input field to give users the admin role (you need a firebase function to do this but you can use `console.log` for now)
- You can use the components in the `Visit` page
- The `roles` doc schema:
```yaml
/roles
  /{user_uid}
    - roles: string
    - assigned_by: string
    - created_at: timestamp
```
